//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace massTurSqlite.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class massTurEntities : DbContext
    {
        public massTurEntities()
            : base("name=massTurEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Tur> Tur { get; set; }
        public virtual DbSet<Tur_Musteri> Tur_Musteri { get; set; }
        public virtual DbSet<Donem> Donem { get; set; }
        public virtual DbSet<Sezon> Sezon { get; set; }
        public virtual DbSet<Parkur> Parkur { get; set; }
    }
}
