//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace massTurSqlite.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteri()
        {
            this.Tur_Musteri = new HashSet<Tur_Musteri>();
        }
    
        public long id { get; set; }
        public string TCMusteriNo { get; set; }
        public string turu { get; set; }
        public Nullable<bool> vatandas { get; set; }
        public string basvuruTipi { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string cinsiyet { get; set; }
        public string dogumYer { get; set; }
        public Nullable<System.DateTime> dogumTarih { get; set; }
        public string anneAd { get; set; }
        public string babaAd { get; set; }
        public string cepTel { get; set; }
        public string medeniDurum { get; set; }
        public string acilNo { get; set; }
        public string acilAd { get; set; }
        public string acilYakinlik { get; set; }
        public Nullable<bool> ogrenci { get; set; }
        public Nullable<bool> ogrenciBelge { get; set; }
        public string adres { get; set; }
        public string faturaAdres { get; set; }
        public Nullable<long> passID { get; set; }
        public Nullable<bool> aktif { get; set; }
        public string grup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tur_Musteri> Tur_Musteri { get; set; }
    }
}
