//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace massTurSqlite.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tur_Musteri
    {
        public long id { get; set; }
        public Nullable<long> turID { get; set; }
        public Nullable<long> musteriID { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Tur Tur { get; set; }
    }
}
